version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: "monthly"
    time: "02:00"
- package-ecosystem: "github-actions"
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: "monthly"
    time: "02:00"
